---
name: Tree-Persist
version: 1.00
author: ~
abstract: ~
license: perl
requires:
  Scalar::Util: 1.10
  Tree: 1.00
  UNIVERSAL::require: 0.10
  perl: 5.6.0
build_requires:
  File::Copy: 0.01
  File::Spec: 0.01
  Scalar::Util: 1.10
  Test::File: 1.10
  Test::File::Cleaner: 0.02
  Test::File::Contents: 0.02
  Test::More: 0.47
provides:
  Tree::Persist:
    file: lib/Tree/Persist.pm
    version: 1.00
  Tree::Persist::Base:
    file: lib/Tree/Persist/Base.pm
    version: 1.00
  Tree::Persist::DB:
    file: lib/Tree/Persist/DB.pm
    version: 1.00
  Tree::Persist::DB::SelfReferential:
    file: lib/Tree/Persist/DB/SelfReferential.pm
    version: 1.00
  Tree::Persist::File:
    file: lib/Tree/Persist/File.pm
    version: 1.00
  Tree::Persist::File::XML:
    file: lib/Tree/Persist/File/XML.pm
    version: 1.00
generated_by: Module::Build version 0.2701
